
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 15 17:59:07 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 21;
  public static final int CONST = 23;
  public static final int GE = 32;
  public static final int EQUALS = 41;
  public static final int CASE = 45;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int MINUS = 11;
  public static final int RPAREN = 7;
  public static final int AND = 19;
  public static final int LT = 33;
  public static final int RECORD = 37;
  public static final int OR = 20;
  public static final int COMMA = 15;
  public static final int CLASS = 42;
  public static final int INC = 28;
  public static final int DIV = 13;
  public static final int PLUS = 10;
  public static final int IF = 52;
  public static final int DOT = 40;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 22;
  public static final int EQUAL = 8;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int MUL = 12;
  public static final int NUMBER = 48;
  public static final int MOD = 14;
  public static final int IDENT = 51;
  public static final int BREAK = 25;
  public static final int VOID = 18;
  public static final int SWITCH = 47;
  public static final int COLON = 38;
  public static final int ELSE = 53;
  public static final int LBRACE = 3;
  public static final int ENUM = 46;
  public static final int READ = 17;
  public static final int CHARCONST = 49;
  public static final int WHILE = 27;
  public static final int NEQUAL = 30;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 39;
  public static final int PROG = 2;
  public static final int DQUESTION = 44;
  public static final int QUESTION = 43;
  public static final int DEC = 29;
  public static final int GT = 31;
  public static final int EXPONENT = 36;
  public static final int PRINT = 16;
  public static final int DO = 26;
}

